name: Policy Checks

on:
  push:

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.52.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      # 1) Gatekeeper YAML’дарын текшерүү
      - name: Run Conftest on Gatekeeper YAML (expect failure)
        continue-on-error: true
        run: |
          conftest test 01-eks-gatekeeper/tests/ \
            --policy 01-eks-gatekeeper/policies

      # 2) Terraform tfplan.json’ду текшерүү
      - name: Run Conftest on Terraform Rego
        run: |
          conftest test 02-conftest-terraform/terraform/tfplan.json \
            --policy 02-conftest-terraform/policies



























   



















































  

  



 

































